name = "ai-video-tool-radar-api"
main = "api.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "ai-video-tool-radar-db"
database_id = "8bedef54-a7ba-4550-b9d0-91a61043f912"
